# UPDATE
version: 1.0.{build}
branches:
    only:
      - master
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
## temporary until 6.0.100-rc.1.21463.6 sdk is installed
install:
  - ps: $urlCurrent = "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0.100-rc.1.21463.6/dotnet-sdk-6.0.100-rc.1.21463.6-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
nuget:
  disable_publish_on_pr: true

build_script:
  - ps: dotnet nuget locals --clear all
  - ps: dotnet restore Bet.CodeAnalyzers.sln -v quiet
  - ps: dotnet build Bet.CodeAnalyzers.sln  --no-restore -p:configuration=Release -p:Version=$($env:appveyor_build_version) -p:GeneratePackageOnBuild=true
  - ps: dotnet pack Bet.CodeAnalyzers.sln  --no-build -p:configuration=Release -p:Version=$($env:appveyor_build_version) -o packages

artifacts:
- path: .\packages\**\*.nupkg
  name: NuGet package

deploy:
- provider: NuGet
  artifact: /NuGet/
  api_key:
    secure: a8sCawSwgb2kYDJAN+xTUvy+MH5jdJR+DmKakUmc/Xom1c+uxyvV+yvpSTJs+ypF
  on:
    branch: master
